---
# Configure All Networks
- name: MSIO | Networking | Libvirt | Install Min2Config Packages Fedora
  include: libvirt_install_fedora.yml
  when: ansible_facts['distribution'] == "Fedora" and ansible_facts['distribution_version']|int <= 32
- name: MSIO | Networking | Libvirt | Install Min2Config Packages RHEL 7
  include: libvirt_install_rhel7.x.yml
  when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_version']|int == 7
- name: MSIO | Networking | Libvirt | Install Min2Config Packages RHEL 8
  include: libvirt_install_rhel8.x.yml
  when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_version']|int == 8
- name: Ensure libvirtd service is started
  systemd:
    name: libvirtd
    state: started
    enabled: yes
  ignore_errors: no
- name: MSIO | Networking | Libvirt | Define Networks
  virt_net:
    command: destroy
    name: default
    state: absent
- name: 'Define OVS Bridge "external" from .xml'
  virt_net:
    command: define
    name: external
    xml: '{{ lookup("template", "libvirt/external.xml") }}'
- name: Build Networking Components - Libvirt Networks
  virt_net:
    command: define
    name: default
    xml: '{{ lookup("template", "libvirt/default.xml") }}'
- name: Define OVS Bridge 'internal' from .xml
  virt_net:
    command: define
    name: internal
    xml: '{{ lookup("template", "libvirt/internal.xml") }}'
- name: Define OVS Bridge 'sparta' from .xml
  virt_net:
    command: define
    name: sparta
    xml: '{{ lookup("template", "libvirt/sparta.xml") }}'
- name: Define OVS Bridge 'ocp' from .xml
  virt_net:
    autostart: yes
    name: "{{ item }}"
  with_items:
    - default
    - external
    - internal
    - sparta
- name: Define OVS Bridge 'ocp' from .xml
  virt_net:
    state: active
    name: "{{ item }}"
  with_items:
    - default
    - external
    - internal
    - sparta
